###########
# Dataset #
###########
dataset: cgca_transition_synthetic_room
eval_datasets: [
    [cgca_transition_synthetic_room, val],
]
test_datasets: [
  [cgca_transition_synthetic_room, test],
]
data_root: ./data/synthetic_room
embedding_root: ./data/embeddings/synthetic/vox_64-step_100k
input_root: ./data/conv_onet
rooms: [room_04, room_05, room_06, room_07, room_08]
data_dim: 3

input_type: 'pointcloud'
pointcloud_noise: 0.005
num_input_sample: 10000

obj_min_rate: # rate to keep for incomplete inputs
buffer_size: 1024
mean_vox_points: 10000

voxel_size: 0.015625  # range of synthetic room is [-0.5, 0.5]
transform:

epoch: 1000000
num_workers: 0

#########
# Model #
#########
model: gca
padding: 2
pad_type: hypercross
z_dim: 32
backbone:
  name: Mink16UNet34C
  kernels: [
      7, 5, 5, 3, 3,
      3, 3, 3, 3, 3
  ]
  init_pretrained:
  in_channels: 1
  out_channels: 1

max_phase: 15
equilibrium_max_phase: 10
sampling_scheme: bernoulli

#########
# Train #
#########
infusion_scheduler:
  type: linear
  initial_rate: 0.1
  speed: 0.005

embedding_loss_weight: 0.01
batch_size: 16

optimizer:
  type: Adam
  options:
    lr: 0.0005
    weight_decay: 0.

clip_grad:
  type: norm
  options:
    max_norm: 0.5

lr_scheduler:
  type: StepLR
  options:
    step_size: 100000000
    gamma: 1.0

completion_rate: 0.95

###########
# Summary #
###########
summary_step: 1000
ckpt_step: 100000

#################
# Visualization #
#################
vis_batch_size: 1
min_vis_step: 20000
vis:
  indices: 3
  vis_collated_imgs:
    step: 25000
    vis_2d:
      axis_ranges: [
        [ -32, 32 ],
        [ -32, 32 ],
        [ -32, 32 ],
      ]
      height: 400
      width: 400
      project_axis: z
      project_center: 0
      project_thres: 1
      alpha: 1.0
      save_tensor: False
      save_tensor_interval: 1000000
    vis_3d:
      axis_ranges: [
        [ -32, 32 ],
        [ -32, 32 ],
        [ -32, 32 ],
      ]
      height: 400
      width: 400
      alpha: 0.3
      scene_capture: False
      save_tensor: False
      save_tensor_interval: 1000000


#########
# Utils #
#########
device: cuda
seed: 0
empty_cache_step: 10

#########
# Debug #
#########
# every step is visualized
debug_vis: False
# every step is evaluated
debug_eval: False
# fit only specified data point
# if not used, leave as blank (None)
overfit_one_ex:

############
# Evaluate #
############
eval_step: 10000
min_eval_step: 0
eval_size: 128
eval_batch_size: 4
max_eval_phase: 15

########
# Test #
########
test_step: 100000
min_test_step: 300000
test_batch_size: 4
test_mode_seeking_phase: 0
test_trials: 5
test_dist_threshold: 0.5
test_sample_num: 100000
cache_only: True
test_save_mesh: False

#########
# Debug #
#########
ones_feat: False
